### ISSUE TITLE
Admin can't change things in Django Admin 

### ISSUE THREAD

**Issue by SaadBazaz** [danyi1212/drf-messages#18]
**Describe the bug**
Works on 3.7 but not 3.6.6 (which is ok)
Although, when enabling ```MESSAGES_USE_SESSIONS = False```, the Admin can't change things (I think because it can't find the Session for the message). What do you suggest?

Here is the error message:

```
Traceback (most recent call last):
  File "/web/src/django/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/web/src/django/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/web/src/django/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/web/src/django/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/web/src/django/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/web/src/django/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/web/src/django/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/web/src/django/django/contrib/admin/options.py", line 1641, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/web/src/django/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/web/src/django/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/web/src/django/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/web/src/django/django/contrib/admin/options.py", line 1573, in _changeform_view
    return self.response_change(request, new_object)
  File "/usr/local/lib/python3.7/site-packages/parler/admin.py", line 361, in response_change
    redirect = super().response_change(request, obj)
  File "/web/src/django/django/contrib/admin/options.py", line 1307, in response_change
    self.message_user(request, msg, messages.SUCCESS)
  File "/web/src/django/django/contrib/admin/options.py", line 1068, in message_user
    messages.add_message(request, level, message, extra_tags=extra_tags, fail_silently=fail_silently)
  File "/web/src/django/django/contrib/messages/api.py", line 34, in add_message
    return messages.add(level, message, extra_tags)
  File "/usr/local/lib/python3.7/site-packages/drf_messages/storage.py", line 121, in add
    Message.objects.create_message(self.request, message, level, extra_tags=extra_tags)
  File "/usr/local/lib/python3.7/site-packages/drf_messages/models.py", line 89, in create_message
    session = Session.objects.get(session_key=request.session.session_key)
  File "/web/src/django/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/web/src/django/django/db/models/query.py", line 417, in get
    self.model._meta.object_name

Exception Type: DoesNotExist at /en/admin/jpnintl/smartcard/48/change/
Exception Value: Session matching query does not exist.
```

**To Reproduce**
1. Set MESSAGE_USE_SESSIONS to False in settings.py
2. Open the admin panel, and login
3. Select an item to change
4. Change something and try to save

**Expected behavior**
It should have saved successfully with a success **message**.

**Project:**
 - OS: Docker on macOS
 - Version: 1.1.0
 - Python Version: 3.7
 - Django Version Unknown
 - DRF Version Unknown

**Comment by danyi1212** [comment]
Hey, can please send the `type(request.session)` and `dir(request.session)`? (from one of your views)

Do you use any custom authentication backend?

**Comment by SaadBazaz** [comment]
Type of request.session: ```<class 'redis_sessions.session.SessionStore'>```
Dir of request.session: ```['TEST_COOKIE_NAME', 'TEST_COOKIE_VALUE', '_SessionBase__not_given', '_SessionBase__session_key', '__class__', '__contains__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_get_new_session_key', '_get_or_create_session_key', '_get_session', '_get_session_key', '_hash', '_session', '_session_cache', '_session_key', '_set_session_key', '_validate_session_key', 'accessed', 'clear', 'clear_expired', 'create', 'cycle_key', 'decode', 'delete', 'delete_test_cookie', 'encode', 'exists', 'flush', 'get', 'get_expire_at_browser_close', 'get_expiry_age', 'get_expiry_date', 'get_real_stored_key', 'get_session_cookie_age', 'has_key', 'is_empty', 'items', 'keys', 'load', 'modified', 'pop', 'save', 'serializer', 'server', 'session_key', 'set_expiry', 'set_test_cookie', 'setdefault', 'test_cookie_worked', 'update', 'values']```

**Comment by SaadBazaz** [comment]
I use FirebaseAuth. If that fails (which it does incase it is an admin), I fallback to SessionAuth.

**Comment by danyi1212** [comment]
It is interesting, seems like you are using a different session backend, something like ([django-redis-sessions](https://pypi.org/project/django-redis-sessions/)), so the problem is more about storing the relation to it.

I need to add support for session engines other than `django.contrib.sessions.backends.db`.
I'll also add some test to cover that use case.

Then you will probably also have the option to use `MESSAGES_USE_SESSIONS = True` if you would like that feature.

**Comment by SaadBazaz** [comment]
Were you able to reproduce the issue?

**Comment by SaadBazaz** [comment]
Changed the the following:
```
SESSION_ENGINE = 'redis_sessions.session'
```

to
```
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
```

And it WORKS! You are right. I think we are in the right direction then. Redis is pretty common, so it'd be great to have that support.

**Comment by danyi1212** [comment]
The PR is actually done. I'll merge it to release 1.1.1 today so you will be able to test it against TestPyPI to make sure it is fixed.

**Comment by SaadBazaz** [comment]
@danyi1212 Awesome stuff. Checked that PR out. Hoping to see it up. I'll test for you.

**Comment by danyi1212** [comment]
Hey, new release available on TestPyPI https://test.pypi.org/project/drf-messages/
